name: Cinepolis
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  http: ^0.13.3
  flutter_staggered_grid_view: ^0.4.0
  cupertino_icons: ^1.0.4
  shared_preferences: ^2.5.2
  mailer: ^6.4.1
  flutter_holo_date_picker: ^1.0.3
  photo_view: ^0.15.0
  qr_flutter: ^4.1.0
  font_awesome_flutter: ^9.2.0
  flutter_rating_bar: ^4.0.0
  horizontal_data_table: ^3.4.3
  flutter_zoom_drawer: ^2.3.0
  fl_chart: ^0.41.0
  syncfusion_flutter_gauges: ^28.2.11
  contained_tab_bar_view: ^0.8.0
  introduction_screen: ^2.1.0
  extended_sliver: ^2.0.1
  badges: ^2.0.2
  flutter_typeahead: ^5.2.0
  syncfusion_flutter_datagrid: ^28.2.11
  dio: ^4.0.4
  flutter_plugin_android_lifecycle: ^2.0.27
  file: ^7.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: any
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.4

flutter_icons:
  image_path: "assets/images/logo_esp_small.jpeg"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/